DROP TABLE IF EXISTS TBL_TRADE;

CREATE TABLE TBL_TRADE (
       TRADE_ID VARCHAR(10) NOT NULL,
       VERSION INTEGER NOT NULL,
       COUNTER_PARTY_ID VARCHAR(10) NOT NULL,
       BOOK_ID VARCHAR(10) NOT NULL,
       MATURITY_DATE DATE NOT NULL,
       CREATED_DATE DATE DEFAULT CURRENT_DATE(),
       EXPIRED BIT DEFAULT FALSE,
       PRIMARY KEY (TRADE_ID,VERSION)
);

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T1',1,'CP-1','B1', DATEADD('DAY',7, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T1',2,'CP-1','B1', DATEADD('DAY',8, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T1',3,'CP-1','B1', DATEADD('DAY',8, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T2',1,'CP-2','B1', DATEADD('DAY',10, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T2',3,'CP-2','B1', DATEADD('DAY',10, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T3',3,'CP-2','B1', DATEADD('DAY',10, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T4',1,'CP-2','B1', DATEADD('DAY',10, CURRENT_DATE));

INSERT INTO TBL_TRADE (TRADE_ID ,VERSION ,COUNTER_PARTY_ID ,BOOK_ID ,MATURITY_DATE )
VALUES ('T4',2,'CP-2','B1', DATEADD('DAY',-5, CURRENT_DATE));
